---
apiVersion: v1
kind: Namespace
metadata:
  name: trousseau
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trousseau-kms-vault
  namespace: trousseau
spec:
  selector:
    matchLabels:
      app: trousseau
  replicas: 1
  template:
    metadata:
      labels:
        app: trousseau
    spec:
      containers:
        - name: trousseau
          image: ghcr.io/trousseau-io/trousseau:dev
