name: Build and push docker image
inputs:
  docker_registry:
    description: "docker registry"
    required: true
  docker_image:
    description: "docker image"
    required: true
  docker_username:
    description: "docker username"
    required: true
  docker_password:
    description: "docker password"
    required: true
  docker_push:
    description: "push docker image"
    required: true
    default: "true"
  docker_tag:
    description: "docker tag"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{inputs.docker_username}}
        password: ${{inputs.docker_password}}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: ${{inputs.docker_push}}
        tags: ${{inputs.docker_registry}}/${{inputs.docker_image}}:${{inputs.docker_tag}}
        cache-from: type=registry,ref=${{inputs.docker_registry}}/${{inputs.docker_image}}:buildcache
        cache-to: type=registry,ref=${{inputs.docker_registry}}/${{inputs.docker_image}}:buildcache,mode=max
