name: build push container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GO111MODULE: on
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v2

      - name: run gosec scan
        uses: securego/gosec@master
        with: 
          CODE_PATH: "./..." 

#       - name: login to dockerhub
#         uses: docker/login-action@v1
#         with: 
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
#       - name: setup buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v1
        
#       - name: build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with: 
#           context: ./
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/trousseau:latest
          
#       - name: image digest
#         run: echo ${{ steps.docker_build.outputs.digests }} 
  
  
